version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/app:cached
    command:
      /bin/bash -c "exec php-fpm"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 remote_autostart=on  remote_port=9010 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=mp.loc"

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/mp.conf:/etc/nginx/conf.d/mp.conf:ro
      - .:/var/app:cached
    ports:
      - "8085:80"
    environment:
      - APP_ENV=dev
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on:
      - php

  db:
    image: postgres:12
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_DB: marketplace
      POSTGRES_PASSWORD: 123456